### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by JackHorse** [zhuohan123/hint-nart#1]
Hi,
I was wondering when will the code be released ?
Regards,
Yash

**Comment by zhuohan123** [comment]
Hi! The code is released for your reference. This codebase was used years ago and was using TensorFlow. Personally I highly recommend using [fairseq](https://github.com/pytorch/fairseq) for research with non-autoregressive MT models. It's much easier to use than the tensor2tensor base two years ago.
